[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
cmds = ["pip install -r dashboard/requirements.txt"]

[phases.build]
dependsOn = ["setup"]

[start]
cmd = "cd dashboard && python -m streamlit run app.py --server.port=8080 --server.address=0.0.0.0"
